language: ruby
services: mongodb
rvm:
  - 1.9.3
  - 2.1.7
  - 2.2.3
  - jruby-19mode

gemfile:
  - Gemfile
  - gemfiles/4.0.gemfile
  - gemfiles/mongoid.gemfile

env:
  global:
    secure: Uco0icktul54bwvQOP4PHME1fKIkWvJTBSYYgLxkJfpT6epeuzRMTs+/vH1Ysvs5s4E2hx2yAYyu2VEu3R5sjxkuPpvQFUJbr8Vxm7g2DczeIL3WlZiSctt0zqJqToyhIW8Fpsza2/GSr1eHkMIk6rnWp4miARtbGAXpH5K4d2s=

sudo: false
