language: ruby
services: mongodb
rvm:
  - 1.9.3
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - ruby-head
  - jruby-19mode

gemfile:
  - Gemfile
  - gemfiles/rails-4.0.gemfile
  - gemfiles/rails-4.1.gemfile
  - gemfiles/rails-4.2.gemfile
  - gemfiles/rails-5.1.gemfile
  - gemfiles/mongoid-4.0.gemfile
  - gemfiles/mongoid-5.0.gemfile
  - gemfiles/mongoid-6.0.gemfile

matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: Gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails-5.1.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/mongoid-6.0.gemfile
    - rvm: 2.4.0
      gemfile: gemfiles/rails-4.0.gemfile
    - rvm: 2.4.0
      gemfile: gemfiles/rails-4.1.gemfile
    - rvm: 2.4.0
      gemfile: gemfiles/mongoid-4.0.gemfile
    - rvm: 2.4.0
      gemfile: gemfiles/mongoid-5.0.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails-4.0.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails-4.1.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/mongoid-4.0.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/mongoid-5.0.gemfile
    - rvm: jruby-19mode
      gemfile: Gemfile
    - rvm: jruby-19mode
      gemfile: gemfiles/rails-5.1.gemfile
    - rvm: jruby-19mode
      gemfile: gemfiles/mongoid-6.0.gemfile


env:
  global:
    secure: Uco0icktul54bwvQOP4PHME1fKIkWvJTBSYYgLxkJfpT6epeuzRMTs+/vH1Ysvs5s4E2hx2yAYyu2VEu3R5sjxkuPpvQFUJbr8Vxm7g2DczeIL3WlZiSctt0zqJqToyhIW8Fpsza2/GSr1eHkMIk6rnWp4miARtbGAXpH5K4d2s=

sudo: false
